question_data = [
    {"text": "C is a high-level programming language.", "answer": "True"},
    {"text": "C++ supports object-oriented programming.", "answer": "True"},
    {"text": "Python is a statically typed language.", "answer": "False"},
    {"text": "In C, 'int* ptr;' declares a pointer to an integer.", "answer": "True"},
    {"text": "The main function is mandatory in every C++ program.", "answer": "True"},
    {"text": "Python supports multiple inheritance.", "answer": "True"},
    {"text": "C does not have built-in support for strings.", "answer": "True"},
    {"text": "C++ has built-in support for exception handling.", "answer": "True"},
    {"text": "Python uses indentation to define blocks of code.", "answer": "True"},
    {"text": "C++ supports operator overloading.", "answer": "True"},
    {"text": "In C, 'printf' is used to take user input.", "answer": "False"},
    {"text": "Python's 'list' is a mutable data type.", "answer": "True"},
    {"text": "C++ does not support function overloading.", "answer": "False"},
    {"text": "C allows functions to return multiple values directly.", "answer": "False"},
    {"text": "Python's 'tuple' is immutable.", "answer": "True"},
    {"text": "C++ uses 'new' and 'delete' for dynamic memory allocation.", "answer": "True"},
    {"text": "In Python, 'self' is a keyword used inside class methods.", "answer": "False"},
    {"text": "C++ supports both compile-time and run-time polymorphism.", "answer": "True"},
    {"text": "The 'malloc' function in C automatically initializes memory to zero.", "answer": "False"},
    {"text": "Python's 'dict' keys must be unique.", "answer": "True"},
    {"text": "C++'s 'vector' is part of the Standard Template Library (STL).", "answer": "True"},
    {"text": "In C, 'scanf' is used to display output on the screen.", "answer": "False"},
    {"text": "Python has built-in support for garbage collection.", "answer": "True"},
    {"text": "C++'s 'friend' function can access private and protected members of a class.", "answer": "True"},
    {"text": "Python's 'set' allows duplicate values.", "answer": "False"},
    {"text": "C++'s 'struct' and 'class' are identical in every way.", "answer": "False"},
    {"text": "Python's 'is' operator checks for object identity, not equality.", "answer": "True"},
    {"text": "C does not support 'namespace' functionality.", "answer": "True"},
    {"text": "In C++, 'cin' is used to take user input.", "answer": "True"},
    {"text": "Python's 'range' function generates lists by default.", "answer": "False"},
    {"text": "In C, 'switch' statements can only work with integer values.", "answer": "True"},
    {"text": "C++ does not have destructors for cleaning up memory.", "answer": "False"},
    {"text": "Python allows functions to return multiple values using tuples.", "answer": "True"},
    {"text": "C++'s 'inline' functions can improve performance by reducing function call overhead.", "answer": "True"},
    {"text": "Python's 'lambda' keyword is used to create anonymous functions.", "answer": "True"},
    {"text": "In C, the 'sizeof' operator returns the size of a variable in bits.", "answer": "False"},
    {"text": "C++ allows default function parameters.", "answer": "True"},
    {"text": "Python allows function arguments to have default values.", "answer": "True"},
    {"text": "C++ supports 'goto' statements, but their use is discouraged.", "answer": "True"},
    {"text": "Python does not support recursion.", "answer": "False"},
    {"text": "C++ templates provide a way to write generic code.", "answer": "True"},
    {"text": "In Python, 'break' statement is used to exit a loop.", "answer": "True"},
    {"text": "C's 'struct' can contain functions.", "answer": "False"},
    {"text": "C++'s 'map' is an ordered associative container.", "answer": "True"},
    {"text": "Python allows both procedural and object-oriented programming.", "answer": "True"},
    {"text": "In C++, an abstract class must have at least one pure virtual function.", "answer": "True"},
    {"text": "Python has built-in support for regular expressions via the 're' module.", "answer": "True"},
    {"text": "In C++, 'public' members of a class can be accessed from outside the class.", "answer": "True"},
    {"text": "Python's 'try-except' block is used for error handling.", "answer": "True"},
    {"text": "C++ does not support type casting.", "answer": "False"}
]